### ISSUE TITLE
Intermittent Device Lost crash in wgpu on wayland 

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1250]
I've now seen this twice in the past 3 days. No specific way to reproduce yet. Both times the entire OS appears to hang and after 5-10 seconds something times out and the app terminates with the below stack trace.

```
$ thread '<unnamed>' panicked at 'Error in Surface::get_current_texture_view: parent device is lost', /home/jleibs/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.15.0/src/backend/direct.rs:316:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: wgpu::backend::direct::Context::handle_error_fatal
   3: <wgpu::backend::direct::Context as wgpu::context::Context>::surface_get_current_texture
   4: <T as wgpu::context::DynContext>::surface_get_current_texture
   5: wgpu::Surface::get_current_texture
   6: egui_wgpu::winit::Painter::paint_and_update_textures
   7: <eframe::native::run::wgpu_integration::WgpuWinitApp as eframe::native::run::WinitApp>::paint
   8: eframe::native::run::run_and_return::{{closure}}
   9: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return
  10: eframe::native::run::run_and_return
  11: std::thread::local::LocalKey<T>::with
  12: eframe::native::run::wgpu_integration::run_wgpu
  13: eframe::run_native
  14: re_viewer::native::run_native_app
  15: tokio::runtime::park::CachedParkThread::block_on
  16: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  17: tokio::runtime::runtime::Runtime::block_on
  18: rerun_bindings::python_bridge::_::__pyfunction_main
  19: pyo3::impl_::trampoline::trampoline_inner
  20: rerun_bindings::python_bridge::_::<impl rerun_bindings::python_bridge::main::MakeDef>::DEF::trampoline
  21: <unknown>
  22: _PyObject_MakeTpCall
  23: _PyEval_EvalFrameDefault
  24: _PyFunction_Vectorcall
  25: _PyEval_EvalFrameDefault
  26: <unknown>
  27: PyEval_EvalCode
  28: <unknown>
  29: <unknown>
  30: _PyEval_EvalFrameDefault
  31: _PyFunction_Vectorcall
  32: _PyEval_EvalFrameDefault
  33: _PyFunction_Vectorcall
  34: <unknown>
  35: Py_RunMain
  36: Py_BytesMain
  37: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  38: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:381:3
  39: _start
  ```

**Comment by Wumpf** [comment]
Potentially related to #3061
