### ISSUE TITLE
re_build_info is failing on pre-releases

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1457]
Pre-releases patch the version number, and end up with a form like: `0.2.0+22d293392.1`:

which is now resulting in:

```
thread '<unnamed>' panicked at 'multi-digit number cannot start with zero', crates/re_build_info/src/rust_version.rs:81:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c9690[54](https://github.com/rerun-io/rerun/actions/runs/4297552794/jobs/7490683781#step:19:55)83/library/core/src/panicking.rs:64:14
   2: re_build_info::rust_version::RustVersion::parse::parse_u8
   3: re_build_info::rust_version::RustVersion::parse
   4: re_log_types::encoding::encoder::Encoder<W>::new
   5: re_sdk::file_writer::FileWriter::new
   6: re_sdk::session::Session::save
   7: rerun_bindings::python_bridge::_::__pyfunction_save
   8: pyo3::impl_::trampoline::trampoline_inner
   9: rerun_bindings::python_bridge::_::<impl rerun_bindings::python_bridge::save::MakeDef>::DEF::trampoline
  10: PyCFunction_Call
  11: _PyObject_MakeTpCall
  12: _PyEval_EvalFrameDefault
  13: _PyFunction_Vectorcall
  14: _PyEval_EvalFrameDefault
  15: _PyFunction_Vectorcall
  16: _PyEval_EvalFrameDefault
  17: _PyFunction_Vectorcall
  18: _PyEval_EvalFrameDefault
  19: _PyEval_EvalCodeWithName
  20: PyEval_EvalCode
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: PyRun_SimpleFileExFlags
  25: Py_RunMain
  26: Py_BytesMain
  27: __libc_start_main
  28: _start
  ```

For all wheel-build jobs on main.

**Comment by jleibs** [comment]
Not sure if we want to fix this by changing the way we compute pre-release versions (https://github.com/rerun-io/rerun/blob/main/scripts/version_util.py#L94) or more robust handling in the parser (or both).
