### ISSUE TITLE
New crash on linux when logging meshes

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1467]
As of https://github.com/rerun-io/rerun/commit/b07149139450f37c584d5fedfd7022f9724461e4 there is a new crash on linux:

This only occurs when we log meshes via the `log_mesh` API.

Can repro by running;
```
python examples/python/raw_mesh/main.py 
```

Stack
```
$ 2023-03-01T22:51:09.178829Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread '<unnamed>' panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_buffer_to_buffer
    Copy error
    copy of 0..23952 would end up overrunning the bounds of the Destination buffer of size 23940

', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.15.0/src/backend/direct.rs:3024:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::ops::function::Fn::call
   3: wgpu::backend::direct::Context::handle_error_nolabel
   4: <wgpu::backend::direct::Context as wgpu::context::Context>::command_encoder_copy_buffer_to_buffer
   5: <T as wgpu::context::DynContext>::command_encoder_copy_buffer_to_buffer
   6: wgpu::CommandEncoder::copy_buffer_to_buffer
   7: re_renderer::allocator::cpu_write_gpu_read_belt::CpuWriteGpuReadBuffer<T>::copy_to_buffer
   8: re_renderer::mesh::GpuMesh::new
   9: re_renderer::resource_managers::mesh_manager::MeshManager::create
  10: re_viewer::misc::mesh_loader::LoadedMesh::load
  11: re_viewer::misc::caches::mesh_cache::MeshCache::load
  12: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  13: re_query::visit::<impl re_query::entity_view::EntityView<Primary>>::visit2
  14: <re_viewer::ui::view_spatial::scene::scene_part::meshes::MeshPart as re_viewer::ui::view_spatial::scene::scene_part::ScenePart>::load
  15: re_viewer::ui::view_spatial::scene::SceneSpatial::load
  16: re_viewer::ui::space_view::SpaceView::scene_ui
  17: <re_viewer::ui::viewport::TabViewer as egui_dock::TabViewer>::ui
  18: egui::containers::frame::Frame::show_dyn
  19: core::ops::function::FnOnce::call_once{{vtable.shim}}
  20: egui::ui::Ui::scope_dyn
  21: egui_dock::DockArea<Tab>::show_inside
  22: core::ops::function::FnOnce::call_once{{vtable.shim}}
  23: egui::ui::Ui::scope_dyn
  24: re_viewer::ui::viewport::Viewport::viewport_ui
```

Seems to happen on both wayland and X11.

I went back to the last successful build when we were still getting wheels: https://github.com/rerun-io/rerun/commit/96b30357a4e12dddd12f063b8af6c0905f181707 and it works just fine there.

The issue is somewhere in this stack: https://github.com/rerun-io/rerun/compare/96b30357a4e12dddd12f063b8af6c0905f181707...b07149139450f37c584d5fedfd7022f9724461e4

https://github.com/rerun-io/rerun/pull/1416 seems to be a likely candidate.

**Comment by Wumpf** [comment]
likely caused by #1416 since buffer size was adjusted there
