### ISSUE TITLE
api_demo main panicked at 'detected re-used `RowId/Timeline`

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1827]
Repro with:
```
$ python examples/python/api_demo/main.py --demo log_cleared

[2023-04-12T17:18:28Z ERROR re_arrow_store::store_write] detected re-used `RowId/Timeline` pair, this is illegal and will lead to undefined behavior in the datastore row_id=17553F8C95107BDF0E6B67CB520C7ED7 timeline=Timeline { name: "log_time", typ: Time } old_time=TimeInt(1681319908921604931) new_time=TimeInt(1681319908921604931)

thread 'ThreadId(1)' panicked at 'detected re-used `RowId/Timeline`', re_arrow_store/src/store_write.rs:249

   6: core::panicking::panic_fmt
             at core/src/panicking.rs:64:14
   7: re_arrow_store::store_write::<impl re_arrow_store::store::DataStore>::insert_row
   8: re_data_store::log_db::EntityDb::add_path_op
             at re_data_store/src/log_db.rs:126:17
      re_data_store::log_db::LogDb::add
             at re_data_store/src/log_db.rs:227:17
   9: re_viewer::app::App::receive_messages
             at re_viewer/src/app.rs:707:35
      <re_viewer::app::App as eframe::epi::App>::update
             at re_viewer/src/app.rs:489:9
  10: eframe::native::epi_integration::EpiIntegration::update::{{closure}}
             at eframe-0.21.3/src/native/epi_integration.rs:454:13
      egui::context::Context::run
             at egui-0.21.0/src/context.rs:286:9
      eframe::native::epi_integration::EpiIntegration::update
             at eframe-0.21.3/src/native/epi_integration.rs:452:27
  11: <eframe::native::run::wgpu_integration::WgpuWinitApp as eframe::native::run::WinitApp>::paint
             at eframe-0.21.3/src/native/run.rs:1223:21
  12: eframe::native::run::run_and_return::{{closure}}
...
```

Also repro's in rust with:
```
cargo run -p api_demo -- --demo log_cleared
```

**Comment by teh-cmc** [comment]
Fixed via https://github.com/rerun-io/rerun/pull/1832
