### ISSUE TITLE
End-to-end tests are unstable on CI

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1855]
The intel-mac e2e tests were failing and in an attempt to unblock our wheel builds, I disabled them in https://github.com/rerun-io/rerun/pull/1853

In the commit *before* disabling the mac builds, the linux e2e were passing. You can see an example successful run here:
 - https://github.com/rerun-io/rerun/commit/3cd534ff0a13e38cb302f780afcfe0a693a7a9fd
 - https://github.com/rerun-io/rerun/actions/runs/4701577971/jobs/8337781980

However after landing the change to disable the tests, the linux tests are now failing as well:
 - https://github.com/rerun-io/rerun/commit/5dc9b61ef7a5f96a5edce3030ebc5314ef6e3b2d
 - https://github.com/rerun-io/rerun/actions/runs/4702053139/jobs/8338847034
 
Running the same commit locally runs fine.

The stack trace here hints at a shutdown race condition, I think related to the multi-processing test.
```
[2023-04-14T17:59:28Z INFO  rerun::run] Received first message.
31
thread 'msg_encoder' panicked at 'Main thread should still be alive: "SendError(..)"', crates/re_sdk_comms/src/buffered_client.rs:203:47
32
stack backtrace:
33
[2023-04-14T17:59:34Z INFO  rerun::run] Successfully ingested 20002 messages.
34
   0: rust_begin_unwind
35
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
36
   1: core::panicking::panic_fmt
37
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
38
   2: core::result::unwrap_failed
39
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
40
   3: re_sdk_comms::buffered_client::msg_encode
```

**Comment by jleibs** [comment]
If there's a regression here (which is unclear since I can't repro locally) this might be a candidate worth looking at: https://github.com/rerun-io/rerun/pull/1830

**Comment by jleibs** [comment]
This workaround has at least hidden the issue: https://github.com/rerun-io/rerun/pull/1857

But I think we should leave this open until we've investigated a bit further. The fact that this did not produce the error that would have been expected is additionally concerning.
