### ISSUE TITLE
Crash when toggling visibility for space-view

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#2593]
Repro with colmap:
```
python examples/python/structure_from_motion/main.py --dataset colmap_fiat
```

Click "toggle visibility" on the "/ (Spatial)" view.

Crash:
```
$ 
thread 'ThreadId(1)' panicked at 'index out of bounds: the len is 1 but the index is 1', 3fff2b0/src/container/grid.rs:194

   6: core::panicking::panic_fmt
             at core/src/panicking.rs:64:14
   7: core::panicking::panic_bounds_check
             at core/src/panicking.rs:159:5
   8: <usize as core::slice::index::SliceIndex<[T]>>::index
             at core/src/slice/index.rs:260:10
      core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at core/src/slice/index.rs:18:9
      <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at alloc/src/vec/mod.rs:2703:9
      egui_tiles::container::grid::Grid::layout
             at 3fff2b0/src/container/grid.rs:194:78
   9: egui_tiles::container::Container::layout
             at 3fff2b0/src/container/mod.rs:220:38
  10: egui_tiles::tiles::Tiles<Pane>::layout_tile
             at 3fff2b0/src/tiles.rs:362:13
  11: egui_tiles::tree::Tree<Pane>::ui
             at 3fff2b0/src/tree.rs:194:13
  12: re_viewport::viewport::Viewport::viewport_ui::{{closure}}
             at re_viewport/src/viewport.rs:564:13
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at core/src/ops/function.rs:250:5
  13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at alloc/src/boxed.rs:1987:9
  14: egui::ui::Ui::scope_dyn
             at egui-0.22.0/src/ui.rs:1732:19
  15: egui::ui::Ui::scope
             at egui-0.22.0/src/ui.rs:1720:9
      re_viewport::viewport::Viewport::viewport_ui
             at re_viewport/src/viewport.rs:554:9
  16: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at alloc/src/boxed.rs:1987:9
  17: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at alloc/src/boxed.rs:1987:9
      egui::containers::frame::Frame::show_dyn
             at egui-0.22.0/src/containers/frame.rs:225:19
  18: egui::containers::frame::Frame::show
             at egui-0.22.0/src/containers/frame.rs:216:9
      egui::containers::panel::CentralPanel::show_inside_dyn
             at egui-0.22.0/src/containers/panel.rs:1022:9
      egui::containers::panel::CentralPanel::show_inside
             at egui-0.22.0/src/containers/panel.rs:1007:9
      re_viewer::app_state::AppState::show::{{closure}}
             at re_viewer/src/app_state.rs:161:17
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at core/src/ops/function.rs:250:5
  19: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at alloc/src/boxed.rs:1987:9
  20: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at alloc/src/boxed.rs:1987:9
      egui::containers::frame::Frame::show_dyn
             at egui-0.22.0/src/containers/frame.rs:225:19
  21: egui::containers::frame::Frame::show
             at egui-0.22.0/src/containers/frame.rs:216:9
      egui::containers::panel::CentralPanel::show_inside_dyn
             at egui-0.22.0/src/containers/panel.rs:1022:9
  22: egui::containers::panel::CentralPanel::show_inside
             at egui-0.22.0/src/containers/panel.rs:1007:9
      re_viewer::app_state::AppState::show
             at re_viewer/src/app_state.rs:141:9
  23: re_viewer::app::App::ui::{{closure}}
             at re_viewer/src/app.rs:530:29
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at core/src/ops/function.rs:250:5
  24: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at alloc/src/boxed.rs:1987:9
  25: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at alloc/src/boxed.rs:1987:9
      egui::containers::frame::Frame::show_dyn
             at egui-0.22.0/src/containers/frame.rs:225:19
  26: egui::containers::frame::Frame::show
             at egui-0.22.0/src/containers/frame.rs:216:9
      egui::containers::panel::CentralPanel::show_inside_dyn
             at egui-0.22.0/src/containers/panel.rs:1022:9
  27: egui::containers::panel::CentralPanel::show_dyn
             at egui-0.22.0/src/containers/panel.rs:1050:30
  28: egui::containers::panel::CentralPanel::show
             at egui-0.22.0/src/containers/panel.rs:1034:9
      re_viewer::app::App::ui
             at re_viewer/src/app.rs:494:9
      <re_viewer::app::App as eframe::epi::App>::update
             at re_viewer/src/app.rs:864:9
  29: eframe::native::epi_integration::EpiIntegration::update::{{closure}}
             at eframe-0.22.0/src/native/epi_integration.rs:500:13
      egui::context::Context::run
             at egui-0.22.0/src/context.rs:374:9
  30: eframe::native::epi_integration::EpiIntegration::update
             at eframe-0.22.0/src/native/epi_integration.rs:498:27
  31: <eframe::native::run::wgpu_integration::WgpuWinitApp as eframe::native::run::WinitApp>::run_ui_and_paint
             at eframe-0.22.0/src/native/run.rs:1281:21
  32: eframe::native::run::run_and_return::{{closure}}
             at eframe-0.22.0/src/native/run.rs:152:17
  33: winit::platform_impl::platform::sticky_exit_callback
      winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return
             at winit-0.28.6/src/platform_impl/linux/wayland/event_loop/mod.rs:549:21
  34: winit::platform_impl::platform::EventLoop<T>::run_return
             at winit-0.28.6/src/platform_impl/linux/mod.rs:785:56
      <winit::event_loop::EventLoop<T> as winit::platform::run_return::EventLoopExtRunReturn>::run_return
             at winit-0.28.6/src/platform/run_return.rs:51:9
      eframe::native::run::run_and_return
             at eframe-0.22.0/src/native/run.rs:132:5
  35: eframe::native::run::wgpu_integration::run_wgpu::{{closure}}
             at eframe-0.22.0/src/native/run.rs:1478:17
      eframe::native::run::with_event_loop::{{closure}}
             at eframe-0.22.0/src/native/run.rs:116:9
      std::thread::local::LocalKey<T>::try_with
             at std/src/thread/local.rs:446:16
      std::thread::local::LocalKey<T>::with
             at std/src/thread/local.rs:422:9
  36: eframe::native::run::with_event_loop
             at eframe-0.22.0/src/native/run.rs:109:5
      eframe::native::run::wgpu_integration::run_wgpu
             at eframe-0.22.0/src/native/run.rs:1475:13
  37: eframe::run_native
             at eframe-0.22.0/src/lib.rs:226:13

Troubleshooting Rerun: https://www.rerun.io/docs/getting-started/troubleshooting
Report bugs: https://github.com/rerun-io/rerun/issues
```

**Comment by emilk** [comment]
Fix coming in:
* https://github.com/rerun-io/egui_tiles/pull/8
