### ISSUE TITLE
panic with relatively large amounts of Linestrip3D

### ISSUE THREAD

**Issue by h3mosphere** [rerun-io/rerun#3193]
**Describe the bug**
Sending large linestrips to rerun causes it to crash with:
thread 'main' panicked at 'range end index 8 out of range for slice of length 0', /home/hemosphere/.cargo/registry/src/github.com-1ecc6299db9ec823/re_renderer-0.8.1/src/allocator/cpu_write_gpu_read_belt.rs:87:9

**To Reproduce**
1. Get stanford bunny: https://www.thingiverse.com/thing:88208/files
2. `git clone https://github.com/h3mosphere/baby_shark.git`
3. `git fetch --all`
4. `git checkout rerun`
5. `cd crates/rerun-examples`
6. `cargo run --release --example simplification -- --input-file Stanford_Bunny.stl -e 0.5 -e 10 -e 50 --mesh-offset 50 --wireframe-offset 100 --wireframe`
7. See panic

**Expected behavior**
The example should not panic

**Backtrace**
```
[2023-09-03T13:58:12Z WARN  re_log_types::data_cell] Unexpected batch for rerun.transform3d
thread 'main' panicked at 'range end index 8 out of range for slice of length 0', /home/hemosphere/.cargo/registry/src/github.com-1ecc6299db9ec823/re_renderer-0.8.1/src/allocator/cpu_write_gpu_read_belt.rs:87:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::slice::index::slice_end_index_len_fail_rt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/slice/index.rs:77:5
   3: core::slice::index::slice_end_index_len_fail
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/slice/index.rs:69:9
   4: <re_renderer::line_strip_builder::LineStripBuilder as core::ops::drop::Drop>::drop
   5: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   6: re_space_view_spatial::parts::lines3d::Lines3DPart::process_entity_view
   7: re_space_view_spatial::parts::entity_iterator::process_entity_views
   8: <re_space_view_spatial::parts::lines3d::Lines3DPart as re_viewer_context::space_view::view_part_system::ViewPartSystem>::execute
   9: re_viewer_context::space_view::space_view_class::<impl re_viewer_context::space_view::dyn_space_view_class::DynSpaceViewClass for T>::ui
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  11: egui::ui::Ui::scope_dyn
  12: re_viewport::space_view::SpaceViewBlueprint::scene_ui
  13: <re_viewport::viewport::TabViewer as egui_tiles::behavior::Behavior<re_viewer_context::SpaceViewId>>::pane_ui
  14: egui_tiles::tree::Tree<Pane>::tile_ui
  15: egui_tiles::container::tabs::Tabs::ui
  16: egui_tiles::container::Container::ui
  17: egui_tiles::tree::Tree<Pane>::tile_ui
  18: egui_tiles::tree::Tree<Pane>::ui
  19: core::ops::function::FnOnce::call_once{{vtable.shim}}
  20: egui::ui::Ui::scope_dyn
  21: re_viewport::viewport::Viewport::viewport_ui
  22: core::ops::function::FnOnce::call_once{{vtable.shim}}
  23: egui::containers::frame::Frame::show_dyn
  24: egui::containers::panel::CentralPanel::show_inside_dyn
  25: core::ops::function::FnOnce::call_once{{vtable.shim}}
  26: core::ops::function::FnOnce::call_once{{vtable.shim}}
  27: egui::containers::frame::Frame::show_dyn
  28: egui::containers::panel::CentralPanel::show_inside_dyn
  29: re_viewer::app_state::AppState::show
  30: core::ops::function::FnOnce::call_once{{vtable.shim}}
  31: core::ops::function::FnOnce::call_once{{vtable.shim}}
  32: egui::containers::frame::Frame::show_dyn
  33: egui::containers::panel::CentralPanel::show_inside_dyn
  34: egui::containers::panel::CentralPanel::show_dyn
  35: <re_viewer::app::App as eframe::epi::App>::update
  36: egui::context::Context::run
  37: eframe::native::epi_integration::EpiIntegration::update
  38: <eframe::native::run::wgpu_integration::WgpuWinitApp as eframe::native::run::WinitApp>::run_ui_and_paint
  39: eframe::native::run::run_and_return::{{closure}}
  40: winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration
  41: winit::platform_impl::platform::x11::EventLoop<T>::run_return
  42: eframe::native::run::run_and_return
  43: std::thread::local::LocalKey<T>::with
  44: eframe::native::run::wgpu_integration::run_wgpu
  45: eframe::run_native
  46: re_viewer::native::run_native_app
  47: rerun::native_viewer::spawn
  48: rerun::clap::RerunArgs::run
  49: simplification::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


```
**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04
 - 
**Rerun version**
0.8.1

**Comment by emilk** [comment]
Hi! This has been fixed in https://github.com/rerun-io/rerun/pull/3093 which will be released in 0.8.2, due out today.
