### ISSUE TITLE
List containing scalar torch tensors does not work for `np.ArrayLike` argument

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#3417]
**Describe the bug**
When passing a list of lists containing scalar tensors (maybe quite uncommon, however, `np.array(...)` works fine) for `child_from_parent` of `log_pinhole` the conversion fails with
```
/home/leo/code/slahmr_rerun/rerun_test.py:11: RerunWarning: Ignoring rerun log call: Traceback (most recent call last):
  File "/home/leo/.pyenv/versions/slahmr/lib/python3.9/site-packages/rerun_sdk/rerun/log_deprecated/log_decorator.py", line 52, in wrapper
    return func(*args, **kwargs)
  File "/home/leo/.pyenv/versions/slahmr/lib/python3.9/site-packages/rerun_sdk/rerun/log_deprecated/camera.py", line 130, in log_pinhole
    arch = Pinhole(
  File "/home/leo/.pyenv/versions/slahmr/lib/python3.9/site-packages/rerun_sdk/rerun/archetypes/pinhole_ext.py", line 98, in __init__
    self.__attrs_init__(image_from_camera=image_from_camera, resolution=resolution)
  File "<attrs generated init rerun.archetypes.pinhole.Pinhole>", line 3, in __attrs_init__
    _setattr('image_from_camera', __attr_converter_image_from_camera(image_from_camera))
  File "/home/leo/.pyenv/versions/slahmr/lib/python3.9/site-packages/rerun_sdk/rerun/_baseclasses.py", line 269, in from_similar
    arr = cls._DELEGATED_ARRAY_TYPE.from_similar(data)
  File "/home/leo/.pyenv/versions/slahmr/lib/python3.9/site-packages/rerun_sdk/rerun/_baseclasses.py", line 157, in from_similar
    pa_array = cls._native_to_pa_array(data, data_type.storage_type)
  File "/home/leo/.pyenv/versions/slahmr/lib/python3.9/site-packages/rerun_sdk/rerun/datatypes/mat3x3.py", line 103, in _native_to_pa_array
    return Mat3x3Ext.native_to_pa_array_override(data, data_type)
  File "/home/leo/.pyenv/versions/slahmr/lib/python3.9/site-packages/rerun_sdk/rerun/datatypes/mat3x3_ext.py", line 57, in native_to_pa_array_override
    matrices = [Mat3x3(m) for m in data]
  File "/home/leo/.pyenv/versions/slahmr/lib/python3.9/site-packages/rerun_sdk/rerun/datatypes/mat3x3_ext.py", line 57, in <listcomp>
    matrices = [Mat3x3(m) for m in data]
  File "/home/leo/.pyenv/versions/slahmr/lib/python3.9/site-packages/rerun_sdk/rerun/datatypes/mat3x3_ext.py", line 25, in __init__
    arr = np.array(rows, dtype=np.float32).reshape(3, 3)
ValueError: cannot reshape array of size 3 into shape (3,3)
```

**To reproduce**
```python
import rerun as rr
import torch
import numpy as np

rr.init("scalar_tensor", spawn=True)

matrix = [[torch.tensor(100.0), 0, 50.0], [0, 100, 50], [0, 0, 1]]

print(np.array(matrix))

rr.log_pinhole(
    "camera/image",
    child_from_parent=matrix,
    width=100,
    height=100,
)
```
Note that the conversion with `np.array(...)` works fine, so I guess such a matrix is a valid `np.ArrayLike`. 

**Desktop (please complete the following information):**
- Ubuntu 20.04

**Rerun version**
```
rerun_py 0.9.0-alpha.4 [rustc 1.72.1 (d5c2e9c34 2023-09-13), LLVM 16.0.5] x86_64-unknown-linux-gnu 2e9df4c, built 2023-09-23T09:59:35Z
```

**Comment by roym899** [comment]
Same issue when `focal_length` or `principal_point` contain a scalar `torch.tensor`
