### ISSUE TITLE
Logging `rr.ClassDescription` fails with TypeError

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#3617]
**Describe the bug**
I'm getting the this error when running the human_pose_tracking example.
```Traceback (most recent call last):
  File "/home/leo/code/rerun/examples/python/human_pose_tracking/main.py", line 206, in <module>
    main()
  File "/home/leo/code/rerun/examples/python/human_pose_tracking/main.py", line 200, in main
    track_pose(video_path, segment=not args.no_segment)
  File "/home/leo/code/rerun/examples/python/human_pose_tracking/main.py", line 55, in track_pose
    rr.log(
  File "/home/leo/.pyenv/versions/rerun/lib/python3.10/site-packages/rerun_sdk/rerun/error_utils.py", line 160, in wrapper
    return func(*args, **kwargs)
  File "/home/leo/.pyenv/versions/rerun/lib/python3.10/site-packages/rerun_sdk/rerun/_log.py", line 147, in log
    components = list(entity)
TypeError: 'ClassDescription' object is not iterable
```

**Rerun version**
```
rerun_py 0.9.0-alpha.6 [rustc 1.72.1 (d5c2e9c34 2023-09-13), LLVM 16.0.5] x86_64-unknown-linux-gnu bde24df, built 2023-10-02T12:51:19Z
```

**Comment by roym899** [comment]
I guess this might already be addressed https://github.com/rerun-io/rerun/pull/3603
