### ISSUE TITLE
Panic with 2D space view and visible time range

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#4979]
1. use the face tracking example (I'm using my good old RRD [1], but probably the example works as well)
2. reset the blueprint
3. select the "video" space view
4. set Visible Time Range to override
5. set "To" to "Absolute Frame"
6. <boom>

[1] https://rerunio.slack.com/archives/C041NHU952S/p1706543181xxxx99?thread_ts=1706204242.101919&cid=C041NHU952S

<img width="2168" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/056df4f3-f342-49e9-8887-f3f64eaa39f3">

**Comment by abey79** [comment]
```

thread 'rayon-1' panicked at 'called `Result::unwrap()` on an `Err` value: ["rerun.components.Position2D", "rerun.components.Color", "rerun.components.Points2DIndicator", "rerun.components.Radius", "rerun.components.ClassId", "rerun.components.DrawOrder", "rerun.components.InstanceKey", "rerun.components.KeypointId", "rerun.components.Text"]'
re_query/src/range.rs:33
stack backtrace:
   8: core::panicking::panic_fmt
             at core/src/panicking.rs:72:14
   9: core::result::unwrap_failed
             at core/src/result.rs:1652:5
  10: core::result::Result<T,E>::unwrap
             at core/src/result.rs:1077:23
      re_query::range::range_archetype
             at re_query/src/range.rs:33:42
  11: re_query_cache::query::<impl re_query_cache::cache::Caches>::query_archetype_pov1_comp5
             at re_query_cache/src/query.rs:160:38
  12: re_query_cache::query::<impl re_query_cache::cache::Caches>::query_archetype_with_history_pov1_comp5
  13: re_space_view_spatial::visualizers::entity_iterator::process_archetype_pov1_comp5
             at re_space_view_spatial/src/visualizers/entity_iterator.rs:186:23
  14: <re_space_view_spatial::visualizers::points2d::Points2DVisualizer as re_viewer_context::space_view::visualizer_system::VisualizerSystem>::execute
             at re_space_view_spatial/src/visualizers/points2d.rs:246:9
  15: re_viewport::system_execution::create_and_run_space_view_systems::{{closure}}
             at re_viewport/src/system_execution.rs:43:19
      core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
             at core/src/ops/function.rs:272:13
  16: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at core/src/ops/function.rs:305:13
      core::option::Option<T>::map
             at core/src/option.rs:1075:29
      <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at core/src/iter/adapters/map.rs:103:26
      rayon::iter::plumbing::Folder::consume_iter
             at rayon-1.7.0/src/iter/plumbing/mod.rs:178:21
  17: <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at rayon-1.7.0/src/iter/map.rs:248:21
      rayon::iter::plumbing::Producer::fold_with
             at rayon-1.7.0/src/iter/plumbing/mod.rs:110:9
      rayon::iter::plumbing::bridge_producer_consumer::helper
             at rayon-1.7.0/src/iter/plumbing/mod.rs:438:13
  18: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at rayon-1.7.0/src/iter/plumbing/mod.rs:418:21
      rayon_core::join::join_context::call_a::{{closure}}
             at rayon-core-1.11.0/src/join/mod.rs:124:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at std/src/panicking.rs:504:40
      std::panicking::try
             at std/src/panicking.rs:468:19
      std::panic::catch_unwind
             at std/src/panic.rs:142:14
      rayon_core::unwind::halt_unwinding
             at rayon-core-1.11.0/src/unwind.rs:17:5
      rayon_core::join::join_context::{{closure}}
             at rayon-core-1.11.0/src/join/mod.rs:142:24
  19: rayon_core::registry::in_worker
             at rayon-core-1.11.0/src/registry.rs:984:13
      rayon_core::join::join_context
             at rayon-core-1.11.0/src/join/mod.rs:132:5
      rayon::iter::plumbing::bridge_producer_consumer::helper
             at rayon-1.7.0/src/iter/plumbing/mod.rs:416:47
  20: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at rayon-1.7.0/src/iter/plumbing/mod.rs:418:21
      rayon_core::join::join_context::call_a::{{closure}}
             at rayon-core-1.11.0/src/join/mod.rs:124:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at std/src/panicking.rs:504:40
      std::panicking::try
             at std/src/panicking.rs:468:19
      std::panic::catch_unwind
             at std/src/panic.rs:142:14
      rayon_core::unwind::halt_unwinding
             at rayon-core-1.11.0/src/unwind.rs:17:5
      rayon_core::join::join_context::{{closure}}
             at rayon-core-1.11.0/src/join/mod.rs:142:24
  21: rayon_core::registry::in_worker
             at rayon-core-1.11.0/src/registry.rs:984:13
      rayon_core::join::join_context
             at rayon-core-1.11.0/src/join/mod.rs:132:5
      rayon::iter::plumbing::bridge_producer_consumer::helper
             at rayon-1.7.0/src/iter/plumbing/mod.rs:416:47
  22: rayon::iter::plumbing::bridge_producer_consumer
             at rayon-1.7.0/src/iter/plumbing/mod.rs:397:12
      <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback
             at rayon-1.7.0/src/iter/plumbing/mod.rs:373:13
      <rayon::vec::Drain<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at rayon-1.7.0/src/vec.rs:147:13
      <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at rayon-1.7.0/src/vec.rs:83:9
  23: rayon::iter::plumbing::bridge
             at rayon-1.7.0/src/iter/plumbing/mod.rs:357:12
      <rayon::vec::IntoIter<T> as rayon::iter::ParallelIterator>::drive_unindexed
             at rayon-1.7.0/src/vec.rs:58:9
      <rayon::collections::hash_map::IterMut<K,V> as rayon::iter::ParallelIterator>::drive_unindexed
             at rayon-1.7.0/src/delegate.rs:21:28
      <rayon::iter::map::Map<I,F> as rayon::iter::ParallelIterator>::drive_unindexed
             at rayon-1.7.0/src/iter/map.rs:49:9
      <rayon::iter::flatten::Flatten<I> as rayon::iter::ParallelIterator>::drive_unindexed
             at rayon-1.7.0/src/iter/flatten.rs:38:9
      rayon::iter::extend::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend
             at rayon-1.7.0/src/iter/extend.rs:576:28
      rayon::iter::from_par_iter::collect_extended
             at rayon-1.7.0/src/iter/from_par_iter.rs:17:5
      rayon::iter::from_par_iter::<impl rayon::iter::FromParallelIterator<T> for alloc::vec::Vec<T>>::from_par_iter
             at rayon-1.7.0/src/iter/from_par_iter.rs:30:9
      rayon::iter::ParallelIterator::collect
             at rayon-1.7.0/src/iter/mod.rs:2056:9
      re_viewport::system_execution::create_and_run_space_view_systems
             at re_viewport/src/system_execution.rs:38:21
  24: re_viewport::space_view::SpaceViewBlueprint::execute_systems
             at re_viewport/src/space_view.rs:452:29
  25: re_viewport::system_execution::execute_systems_for_space_views::{{closure}}::{{closure}}::{{closure}}
             at re_viewport/src/system_execution.rs:80:29
      core::option::Option<T>::map
             at core/src/option.rs:1075:29
      re_viewport::system_execution::execute_systems_for_space_views::{{closure}}::{{closure}}
             at re_viewport/src/system_execution.rs:77:21
      core::option::Option<T>::and_then
             at core/src/option.rs:1414:24
      re_viewport::system_execution::execute_systems_for_space_views::{{closure}}
             at re_viewport/src/system_execution.rs:75:13
      <rayon::iter::filter_map::FilterMapFolder<C,P> as rayon::iter::plumbing::Folder<T>>::consume
             at rayon-1.7.0/src/iter/filter_map.rs:123:36
  26: rayon::iter::plumbing::Folder::consume_iter
             at rayon-1.7.0/src/iter/plumbing/mod.rs:179:20
      rayon::iter::plumbing::Producer::fold_with
             at rayon-1.7.0/src/iter/plumbing/mod.rs:110:9
      rayon::iter::plumbing::bridge_producer_consumer::helper
             at rayon-1.7.0/src/iter/plumbing/mod.rs:438:13
  27: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at rayon-1.7.0/src/iter/plumbing/mod.rs:418:21
      rayon_core::join::join_context::call_a::{{closure}}
             at rayon-core-1.11.0/src/join/mod.rs:124:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at std/src/panicking.rs:504:40
      std::panicking::try
             at std/src/panicking.rs:468:19
      std::panic::catch_unwind
             at std/src/panic.rs:142:14
      rayon_core::unwind::halt_unwinding
             at rayon-core-1.11.0/src/unwind.rs:17:5
      rayon_core::join::join_context::{{closure}}
             at rayon-core-1.11.0/src/join/mod.rs:142:24
  28: rayon_core::registry::in_worker
             at rayon-core-1.11.0/src/registry.rs:984:13
      rayon_core::join::join_context
             at rayon-core-1.11.0/src/join/mod.rs:132:5
      rayon::iter::plumbing::bridge_producer_consumer::helper
             at rayon-1.7.0/src/iter/plumbing/mod.rs:416:47
  29: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at rayon-1.7.0/src/iter/plumbing/mod.rs:427:21
      rayon_core::join::join_context::call_b::{{closure}}
             at rayon-core-1.11.0/src/join/mod.rs:129:25
      rayon_core::job::StackJob<L,F,R>::run_inline
             at rayon-core-1.11.0/src/job.rs:102:9
  30: rayon_core::join::join_context::{{closure}}
             at rayon-core-1.11.0/src/join/mod.rs:159:36
  31: rayon_core::registry::in_worker
             at rayon-core-1.11.0/src/registry.rs:984:13
      rayon_core::join::join_context
             at rayon-core-1.11.0/src/join/mod.rs:132:5
      rayon::iter::plumbing::bridge_producer_consumer::helper
             at rayon-1.7.0/src/iter/plumbing/mod.rs:416:47
  32: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at rayon-1.7.0/src/iter/plumbing/mod.rs:427:21
      rayon_core::join::join_context::call_b::{{closure}}
             at rayon-core-1.11.0/src/join/mod.rs:129:25
      rayon_core::job::JobResult<T>::call::{{closure}}
             at rayon-core-1.11.0/src/job.rs:218:41
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at std/src/panicking.rs:504:40
      std::panicking::try
             at std/src/panicking.rs:468:19
      std::panic::catch_unwind
             at std/src/panic.rs:142:14
      rayon_core::unwind::halt_unwinding
             at rayon-core-1.11.0/src/unwind.rs:17:5
      rayon_core::job::JobResult<T>::call
             at rayon-core-1.11.0/src/job.rs:218:15
      <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
             at rayon-core-1.11.0/src/job.rs:120:32
  33: rayon_core::job::JobRef::execute
             at rayon-core-1.11.0/src/job.rs:64:9
      rayon_core::registry::WorkerThread::execute
             at rayon-core-1.11.0/src/registry.rs:874:13
      rayon_core::registry::WorkerThread::wait_until_cold
             at rayon-core-1.11.0/src/registry.rs:820:22
  34: rayon_core::registry::WorkerThread::wait_until
             at rayon-core-1.11.0/src/registry.rs:803:13
      rayon_core::registry::main_loop
             at rayon-core-1.11.0/src/registry.rs:948:5
      rayon_core::registry::ThreadBuilder::run
             at rayon-core-1.11.0/src/registry.rs:54:18
  35: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}
             at rayon-core-1.11.0/src/registry.rs:99:20

Troubleshooting Rerun: https://www.rerun.io/docs/getting-started/troubleshooting
Report bugs: https://github.com/rerun-io/rerun/issues

Process finished with exit code 102
```
