### ISSUE TITLE
Crash when removing SpaceView: thread 'main' panicked at 'assertion failed: clear_cascade.is_empty()'

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#5426]
```
thread 'main' panicked at 'assertion failed: clear_cascade.is_empty()'
re_entity_db/src/entity_db.rs:343
stack backtrace:
   6: core::panicking::panic_fmt
             at core/src/panicking.rs:72:14
   7: core::panicking::panic
             at core/src/panicking.rs:127:5
   8: re_entity_db::entity_db::EntityDb::add_data_row
             at re_entity_db/src/entity_db.rs:343:9
   9: re_viewer::app::App::run_system_command
             at re_viewer/src/app.rs:393:31
      re_viewer::app::App::run_pending_system_commands
             at re_viewer/src/app.rs:315:13
      <re_viewer::app::App as eframe::epi::App>::update
             at re_viewer/src/app.rs:1308:9
  10: eframe::native::epi_integration::EpiIntegration::update::{{closure}}
             at eframe/src/native/epi_integration.rs:284:17
      egui::context::Context::run
             at egui/src/context.rs:751:9
  11: eframe::native::epi_integration::EpiIntegration::update
             at eframe/src/native/epi_integration.rs:277:27
  12: eframe::native::wgpu_integration::WgpuWinitRunning::run_ui_and_paint
             at eframe/src/native/wgpu_integration.rs:632:27
      <eframe::native::wgpu_integration::WgpuWinitApp as eframe::native::winit_integration::WinitApp>::run_ui_and_paint
             at eframe/src/native/wgpu_integration.rs:395:13
  13: eframe::native::run::run_and_return::{{closure}}
             at eframe/src/native/run.rs:99:17
      core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at core/src/ops/function.rs:294:13
  14: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at core/src/ops/function.rs:294:13
      winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::single_iteration
             at winit-0.29.9/src/platform_impl/linux/wayland/event_loop/mod.rs:504:17
      winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::poll_events_with_timeout
             at winit-0.29.9/src/platform_impl/linux/wayland/event_loop/mod.rs:323:9
      winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::pump_events
             at winit-0.29.9/src/platform_impl/linux/wayland/event_loop/mod.rs:237:13
  15: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_on_demand
             at winit-0.29.9/src/platform_impl/linux/wayland/event_loop/mod.rs:201:19
  16: winit::platform_impl::platform::EventLoop<T>::run_on_demand
             at winit-0.29.9/src/platform_impl/linux/mod.rs:821:56
  17: <winit::event_loop::EventLoop<T> as winit::platform::run_on_demand::EventLoopExtRunOnDemand>::run_on_demand
             at winit-0.29.9/src/platform/run_on_demand.rs:80:9
      eframe::native::run::run_and_return
             at eframe/src/native/run.rs:76:5
      eframe::native::run::run_wgpu::{{closure}}
             at eframe/src/native/run.rs:423:13
      eframe::native::run::with_event_loop::{{closure}}
             at eframe/src/native/run.rs:58:12
      std::thread::local::LocalKey<T>::try_with
             at std/src/thread/local.rs:270:16
      std::thread::local::LocalKey<T>::with
             at std/src/thread/local.rs:246:9
      eframe::native::run::with_event_loop
             at eframe/src/native/run.rs:48:16
      eframe::native::run::run_wgpu
             at eframe/src/native/run.rs:421:16
  18: eframe::run_native
             at eframe/src/lib.rs:268:13
```

This reproduces trivially by removing a space-view.

Run any example. e.g.
```
python examples/python/dna/main.py
```

Click the "-" button to removew a space-view, such as "description".

Crash.

**Comment by jleibs** [comment]
- Bisected to: https://github.com/rerun-io/rerun/pull/5413
