### ISSUE TITLE
Sending a blueprint withan empty barchart crashes the viewer

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#6681]
Repro:
```
import rerun.blueprint as rrb
import rerun as rr

rr.init("rerun_example_crash", spawn=True)

uhoh = rrb.Blueprint(
    rrb.BarChartView(contents=["fft"]),
)

rr.send_blueprint(uhoh)
```

Crashes on 0.17 but does not crash on 0.16.1.

Both on native (linux) and web.

Stack trace:
```
[2024-06-29T00:10:36Z DEBUG re_viewer::app] Opening a new recording: 5ffa5d9c-6d50-4315-a3ad-9ce66665807f
[2024-06-29T00:10:36Z DEBUG re_viewer::app] Data source tcp://127.0.0.1:55288 has finished
[2024-06-29T00:10:36Z DEBUG re_viewer::app] Data source tcp://127.0.0.1:55286 has finished
[2024-06-29T00:10:36Z DEBUG re_viewer::app] Opening a new recording: 5ffa5d9c-6d50-4315-a3ad-9ce66665807f
[2024-06-29T00:10:36Z DEBUG re_entity_db::store_bundle] Creating new store: 704db980-ef70-4f92-b73a-74df056c06ce
[2024-06-29T00:10:36Z DEBUG re_viewer::app] Activating blueprint that was loaded from TCP server, port 9876
[2024-06-29T00:10:36Z DEBUG re_viewer_context::store_hub] Switching default blueprint for rerun_example_crash to 704db980-ef70-4f92-b73a-74df056c06ce
[2024-06-29T00:10:36Z DEBUG re_viewer_context::store_hub] Cloning 704db980-ef70-4f92-b73a-74df056c06ce as 50d716a6-e0fb-4cf3-8597-b8ab33f78f28 the active blueprint for rerun_example_crash to 704db980-ef70-4f92-b73a-74df056c06ceam is closed
[2024-06-29T00:10:36Z DEBUG re_viewer::app] Data source tcp://127.0.0.1:55296 has finished
During handling of the above exception, another exception occurred:
thread 'main' panicked at 'assertion failed: max > min'
egui_plot/src/lib.rs:1766
stack backtrace:
   6: core::panicking::panic_fmt
             at core/src/panicking.rs:72:14
   7: core::panicking::panic
             at core/src/panicking.rs:144:5
   8: egui_plot::fill_marks_between
             at egui_plot/src/lib.rs:1766:5
      egui_plot::generate_marks
             at egui_plot/src/lib.rs:1736:5
   9: egui_plot::log_grid_spacer::{{closure}}
             at egui_plot/src/lib.rs:1434:9
  10: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at alloc/src/boxed.rs:2029:9
      egui_plot::Plot::show_dyn
             at egui_plot/src/lib.rs:1147:13
  11: egui_plot::Plot::show
             at egui_plot/src/lib.rs:728:9
      <re_space_view_bar_chart::space_view_class::BarChartSpaceView as re_viewer_context::space_view::space_view_class::SpaceViewClass>::ui::{{closure}}
             at re_space_view_bar_chart/src/space_view_class.rs:169:17
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at core/src/ops/function.rs:250:5
  12: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at alloc/src/boxed.rs:2015:9
  13: egui::ui::Ui::scope_dyn
             at egui/src/ui.rs:2005:19
  14: egui::ui::Ui::scope
             at egui/src/ui.rs:1991:9
  15: <re_space_view_bar_chart::space_view_class::BarChartSpaceView as re_viewer_context::space_view::space_view_class::SpaceViewClass>::ui
             at re_space_view_bar_chart/src/space_view_class.rs:154:9
```

**Comment by jleibs** [comment]
Things to investigate:
 - egui_plots has been updated
 - aspects of fallback values have been changed that could cause us to be sending different data to egui_plots in this case.

**Comment by Wumpf** [comment]
that's a debug assertion only, fixed it for the time series chart already but didn't realize there it was new

**Comment by emilk** [comment]
We also hit a `debug_assertion` just loading the plots example

**Comment by emilk** [comment]
>  fixed it for the time series chart already but didn't realize there it was new

@Wumpf is referring to https://github.com/rerun-io/rerun/pull/6639/files

I don't really understand why `scalar_axis.component_or_fallback` returns an inverted range though

**Comment by emilk** [comment]
I believe this has something to do with empty plots, and how to pick bounds for such plots

**Comment by Wumpf** [comment]
Doesn't have to be inverted, a zero size range is enough to trigger the assertion. (A user may though provide an inverted range, we have to guard for that as well)

**Comment by emilk** [comment]
When I run `check_all_components_ui.py`, `scalar_axis.component_or_fallback::<Range1D>` return the range `(3.0000000000000004, 3.0)` - I wan't to understand why.

**Comment by emilk** [comment]
I suspect this is to blame: https://github.com/rerun-io/rerun/blob/9c4df0b8abd62929915ded783e377285a716ac0c/crates/re_space_view_time_series/src/space_view_class.rs#L665
