### ISSUE TITLE
Fix broken examples

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#6901]
The following examples fail, at least on CI:

* `arkit_scenes` (ImportError: libEGL.so.1: cannot open shared object file: No such file or directory)
* `human_pose_tracking`
* `nuscenes_dataset`
* `segment_anything_model`
* `structure_from_motion` (ImportError: libEGL.so.1: cannot open shared object file: No such file or directory)

### `human_pose_tracking`
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/work/rerun/rerun/examples/python/human_pose_tracking/human_pose_tracking.py", line 15, in <module>
    import mediapipe as mp
  File "/home/runner/work/rerun/rerun/.pixi/envs/wheel-test/lib/python3.11/site-packages/mediapipe/__init__.py", line 16, in <module>
    import mediapipe.python.solutions as solutions 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/rerun/rerun/.pixi/envs/wheel-test/lib/python3.11/site-packages/mediapipe/python/solutions/__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "/home/runner/work/rerun/rerun/.pixi/envs/wheel-test/lib/python3.11/site-packages/mediapipe/python/solutions/drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "/home/runner/work/rerun/rerun/.pixi/envs/wheel-test/lib/python3.11/site-packages/mediapipe/python/solutions/drawing_utils.py", line 21, in <module>
    import matplotlib.pyplot as plt
  File "/home/runner/work/rerun/rerun/.pixi/envs/wheel-test/lib/python3.11/site-packages/matplotlib/__init__.py", line 210, in <module>
    _check_versions()
  File "/home/runner/work/rerun/rerun/.pixi/envs/wheel-test/lib/python3.11/site-packages/matplotlib/__init__.py", line 195, in _check_versions
    from . import ft2font
ImportError: /home/runner/work/rerun/rerun/.pixi/envs/wheel-test/lib/python3.11/site-packages/matplotlib/ft2font.cpython-311-x86_64-linux-gnu.so: undefined symbol: FT_Load_Glyph
```

### `nuscenes_dataset`
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/work/rerun/rerun/examples/python/nuscenes_dataset/nuscenes_dataset/__main__.py", line 8, in <module>
    import matplotlib
  File "/home/runner/work/rerun/rerun/.pixi/envs/wheel-test/lib/python3.11/site-packages/matplotlib/__init__.py", line 210, in <module>
    _check_versions()
  File "/home/runner/work/rerun/rerun/.pixi/envs/wheel-test/lib/python3.11/site-packages/matplotlib/__init__.py", line 195, in _check_versions
    from . import ft2font
ImportError: /home/runner/work/rerun/rerun/.pixi/envs/wheel-test/lib/python3.11/site-packages/matplotlib/ft2font.cpython-311-x86_64-linux-gnu.so: undefined symbol: FT_Load_Glyph
```

### `segment_anything_model`
In https://github.com/rerun-io/rerun/pull/6900 I disabled the `segment_anything_model` example from building on CI, because it is broken.

The `segment_anything_model` example exits with a non-zero, without explaining why. It's this that does it:
https://github.com/rerun-io/rerun/blob/27b48c3333ef15bfab763b59dcd106bc6b49d826/examples/python/segment_anything_model/segment_anything_model.py#L78

Repro:

```
pixi run -e examples py-build-examples
pixi run -e examples python3 -m segment_anything_model --save example_data/segment_anything_model.rrd
```

The CI is running
```
pixi run -e examples build-examples rrd --channel nightly example_data 
```

Note that `py-build-examples` is not the same as `build-examples`. It's confusing.

**Comment by jleibs** [comment]
In the future, it would be very helpful to:
1. Cite the specific action.yml file that is failing.
2. Link to a failed build run for additional context.

**Comment by jleibs** [comment]
These all run for me now. Closing this issue. Folks can open new issues with concrete repros as necessary.
