### ISSUE TITLE
Crash in `slice::from_raw_parts`

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#7236]
No repro yet

```
thread 'rayon-10' panicked at 'unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`'
core/src/panicking.rs:219
stack backtrace:
   1: re_crash_handler::callstack_from
             at re_crash_handler/src/lib.rs:223:21
   2: re_crash_handler::install_panic_hook::{{closure}}
             at re_crash_handler/src/lib.rs:30:25
   3: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at alloc/src/boxed.rs:2077:9
      std::panicking::rust_panic_with_hook
             at std/src/panicking.rs:799:13
   4: std::panicking::begin_panic_handler::{{closure}}
             at std/src/panicking.rs:656:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at std/src/sys_common/backtrace.rs:171:18
   6: rust_begin_unwind
             at std/src/panicking.rs:652:5
   7: core::panicking::panic_nounwind_fmt::runtime
             at core/src/panicking.rs:110:18
      core::panicking::panic_nounwind_fmt
             at core/src/panicking.rs:120:5
   8: core::panicking::panic_nounwind
             at core/src/panicking.rs:219:5
   9: re_renderer::allocator::uniform_buffer_fill::create_and_fill_uniform_buffer_batch
  10: re_renderer::renderer::point_cloud::PointCloudDrawData::new
             at re_renderer/src/renderer/point_cloud.rs:271:43
  11: <re_space_view_spatial::visualizers::points3d::Points3DVisualizer as re_viewer_context::space_view::visualizer_system::VisualizerSystem>::execute
             at re_space_view_spatial/src/visualizers/points3d.rs:265:13
  12: re_viewport::system_execution::run_space_view_systems::{{closure}}
             at re_viewport/src/system_execution.rs:44:19
```

**Comment by emilk** [comment]
* Cause: https://github.com/purpleprotocol/mimalloc_rust/issues/128

We've worked around this on `main`, and have also update mimalloc
