### ISSUE TITLE
debug assertion in query when sending the same data twice

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#7772]
Followed the new getting started guide and sent data from a face_detection demo twice by running this snippet twice _after_ loading the original recording first:

* open rerun (in debug)
* load data.rrd in it
* run below script
* run below script
* -> rerun crashes ... sometimes?? can't get it to fail anymore

```
import rerun as rr

recording = rr.dataframe.load_recording("../data.rrd")
view = recording.view(index="frame_nr", contents="/blendshapes/0/jawOpen")
table = view.select().read_all()

df = table.to_pandas()
df["jawOpen"] = df["/blendshapes/0/jawOpen:Scalar"].explode().astype(float)
df["jawOpenState"] = df["jawOpen"] > 0.15

rr.init(
    recording.application_id(),
    recording_id=recording.recording_id(),
)
rr.spawn()
rr.send_columns(
    "/jaw_open_state",
    times=[rr.TimeSequenceColumn("frame_nr", df["frame_nr"])],
    components=[
        rr.components.ScalarBatch(df["jawOpenState"]),
    ],
)
```

Full callstack:
```
thread 'main' panicked at 'the query cache should have already taken care of sorting (and densifying!) the chunk'
re_dataframe/src/query.rs:621
stack backtrace:
   8: core::panicking::panic_fmt
             at core/src/panicking.rs:72
   9: re_dataframe::query::impl$1::fetch_chunks::closure$0::closure$0
             at re_dataframe/src/query.rs:621
      core::iter::adapters::map::map_fold::closure$0
             at core/src/iter/adapters/map.rs:89
      core::iter::traits::iterator::Iterator::fold
             at core/src/iter/traits/iterator.rs:2588
      core::iter::adapters::map::impl$2::fold<tuple$<core::sync::atomic::AtomicU64,re_chunk::chunk::Chunk>,alloc::vec::into_iter::IntoIter<re_chunk::chunk::Chunk,alloc::alloc::Global>,re_dataframe::query::impl$1::fetch_chunks::closure$0::closure_env$0<1>,tuple$
             at core/src/iter/adapters/map.rs:129
  10: core::iter::traits::iterator::Iterator::for_each
             at core/src/iter/traits/iterator.rs:818
      alloc::vec::Vec<tuple$<core::sync::atomic::AtomicU64,re_chunk::chunk::Chunk>,alloc::alloc::Global>::extend_trusted<tuple$<core::sync::atomic::AtomicU64,re_chunk::chunk::Chunk>,alloc::alloc::Global,core::iter::adapters::map::Map<alloc::vec::into_iter::Into
             at alloc/src/vec/mod.rs:3098
  11: alloc::vec::spec_extend::impl$1::spec_extend
             at alloc/src/vec/spec_extend.rs:26
      alloc::vec::spec_from_iter_nested::impl$1::from_iter<tuple$<core::sync::atomic::AtomicU64,re_chunk::chunk::Chunk>,core::iter::adapters::map::Map<alloc::vec::into_iter::IntoIter<re_chunk::chunk::Chunk,alloc::alloc::Global>,re_dataframe::query::impl$1::fetc
             at alloc/src/vec/spec_from_iter_nested.rs:62
  12: alloc::vec::in_place_collect::impl$1::from_iter
             at alloc/src/vec/in_place_collect.rs:245
      alloc::vec::impl$15::from_iter
             at alloc/src/vec/mod.rs:2972
      core::iter::traits::iterator::Iterator::collect
             at core/src/iter/traits/iterator.rs:2004
      itertools::Itertools::collect_vec
             at itertools-0.13.0/src/lib.rs:2227
      re_dataframe::query::impl$1::fetch_chunks::closure$0
             at re_dataframe/src/query.rs:611
      enum2$<core::option::Option<tuple$<re_types_core::loggable::ComponentName,alloc::vec::Vec<re_chunk::chunk::Chunk,alloc::alloc::Global> > > >::map
             at core/src/option.rs:1072
      re_dataframe::query::QueryHandle::fetch_chunks<1>
             at re_dataframe/src/query.rs:606
  13: re_dataframe::query::impl$1::fetch_view_chunks::closure$1
             at re_dataframe/src/query.rs:464
      core::iter::adapters::map::map_fold::closure$0
             at core/src/iter/adapters/map.rs:89
      core::iter::adapters::enumerate::impl$1::fold::enumerate::closure$0
             at core/src/iter/adapters/enumerate.rs:108
      core::slice::iter::impl$181::fold
             at core/src/slice/iter/macros.rs:230
      core::iter::adapters::enumerate::impl$1::fold
             at core/src/iter/adapters/enumerate.rs:114
      core::iter::adapters::map::impl$2::fold<alloc::vec::Vec<tuple$<core::sync::atomic::AtomicU64,re_chunk::chunk::Chunk>,alloc::alloc::Global>,core::iter::adapters::enumerate::Enumerate<core::slice::iter::Iter<enum2$<re_chunk_store::dataframe::ColumnDescripto
             at core/src/iter/adapters/map.rs:129
  14: core::iter::traits::iterator::Iterator::for_each
             at core/src/iter/traits/iterator.rs:818
      alloc::vec::Vec<alloc::vec::Vec<tuple$<core::sync::atomic::AtomicU64,re_chunk::chunk::Chunk>,alloc::alloc::Global>,alloc::alloc::Global>::extend_trusted
             at alloc/src/vec/mod.rs:3098
      alloc::vec::spec_extend::impl$1::spec_extend
             at alloc/src/vec/spec_extend.rs:26
      alloc::vec::spec_from_iter_nested::impl$1::from_iter<alloc::vec::Vec<tuple$<core::sync::atomic::AtomicU64,re_chunk::chunk::Chunk>,alloc::alloc::Global>,core::iter::adapters::map::Map<core::iter::adapters::enumerate::Enumerate<core::slice::iter::Iter<enum2
             at alloc/src/vec/spec_from_iter_nested.rs:62
  15: alloc::vec::spec_from_iter::impl$0::from_iter
             at alloc/src/vec/spec_from_iter.rs:33
      alloc::vec::impl$15::from_iter
             at alloc/src/vec/mod.rs:2972
      core::iter::traits::iterator::Iterator::collect
             at core/src/iter/traits/iterator.rs:2004
      re_dataframe::query::QueryHandle::fetch_view_chunks
             at re_dataframe/src/query.rs:457
      re_dataframe::query::QueryHandle::init_
             at re_dataframe/src/query.rs:215
  16: re_dataframe::query::impl$1::init::closure$0
             at re_dataframe/src/query.rs:159
      std::sync::once_lock::impl$0::get_or_init::closure$0
             at std/src/sync/once_lock.rs:250
      std::sync::once_lock::impl$0::initialize::closure$0
             at std/src/sync/once_lock.rs:457
      std::sync::once::impl$2::call_once_force::closure$0
             at std/src/sync/once.rs:208
      core::ops::function::FnOnce::call_once
             at core/src/ops/function.rs:250
      core::ops::function::FnOnce::call_once<std::sync::once::impl$2::call_once_force::closure_env$0<std::sync::once_lock::impl$0::initialize::closure_env$0<re_dataframe::query::QueryHandleState,std::sync::once_lock::impl$0::get_or_init::closure_env$0<re_datafr
             at std/src/sync/once.rs:208
  17: std::sys::sync::once::queue::Once::call
             at std/src/sys/sync/once/queue.rs:183
  18: std::sync::once::Once::call_once_force
             at std/src/sync/once.rs:208
      std::sync::once_lock::OnceLock<re_dataframe::query::QueryHandleState>::initialize<re_dataframe::query::QueryHandleState,std::sync::once_lock::impl$0::get_or_init::closure_env$0<re_dataframe::query::QueryHandleState,re_dataframe::query::impl$1::init::closu
             at std/src/sync/once_lock.rs:456
  19: std::sync::once_lock::OnceLock<re_dataframe::query::QueryHandleState>::get_or_try_init    
             at std/src/sync/once_lock.rs:338
      std::sync::once_lock::OnceLock<re_dataframe::query::QueryHandleState>::get_or_init        
             at std/src/sync/once_lock.rs:250
      re_dataframe::query::QueryHandle::init
             at re_dataframe/src/query.rs:159
  20: re_dataframe::query::QueryHandle::selected_contents
             at re_dataframe/src/query.rs:658
      re_space_view_dataframe::dataframe_ui::dataframe_ui
             at re_space_view_dataframe/src/dataframe_ui.rs:40
  21: re_space_view_dataframe::space_view_class::impl$1::ui
             at re_space_view_dataframe/src/space_view_class.rs:169
  22: re_viewport::viewport::impl$1::pane_ui::closure$2
             at re_viewport/src/viewport.rs:546
      core::ops::function::FnOnce::call_once<re_viewport::viewport::impl$1::pane_ui::closure_env$2,tuple$<ref_mut$<egui::ui::Ui> > >
             at core/src/ops/function.rs:250
  23: alloc::boxed::impl$48::call_once<tuple$<ref_mut$<egui::ui::Ui> >,dyn$<core::ops::function::FnOnce<tuple$<ref_mut$<egui::ui::Ui> >,assoc$<Output,tuple$<> > > >,alloc::alloc::Global>      
             at alloc/src/boxed.rs:2022
  24: egui::ui::Ui::scope_dyn<tuple$<> >
             at egui-0.29.1/src/ui.rs:2292
  25: egui::ui::Ui::scope<tuple$<>,re_viewport::viewport::impl$1::pane_ui::closure_env$2>       
             at egui-0.29.1/src/ui.rs:2271
  26: re_viewport::viewport::impl$1::pane_ui
             at re_viewport/src/viewport.rs:545
  27: egui_tiles::tree::impl$1::tile_ui::closure$0
             at egui_tiles-0.10.1/src/tree.rs:392
      egui::ui::impl$7::add_enabled_ui::closure$0
             at egui-0.29.1/src/ui.rs:1680
      core::ops::function::FnOnce::call_once<egui::ui::impl$7::add_enabled_ui::closure_env$0<tuple$<>,egui_tiles::tree::impl$1::tile_ui::closure_env$0<re_viewer_context::blueprint_id::BlueprintId<re_viewer_context::blueprint_id::SpaceViewIdRegistry> > >,tuple$<
             at core/src/ops/function.rs:250
  28: alloc::boxed::impl$48::call_once<tuple$<ref_mut$<egui::ui::Ui> >,dyn$<core::ops::function::FnOnce<tuple$<ref_mut$<egui::ui::Ui> >,assoc$<Output,tuple$<> > > >,alloc::alloc::Global>      
             at alloc/src/boxed.rs:2022
  29: egui::ui::Ui::scope_dyn<tuple$<> >
             at egui-0.29.1/src/ui.rs:2292
  30: egui::ui::Ui::scope<tuple$<>,egui::ui::impl$7::add_enabled_ui::closure_env$0<tuple$<>,egui_tiles::tree::impl$1::tile_ui::closure_env$0<re_viewer_context::blueprint_id::BlueprintId<re_viewer_context::blueprint_id::SpaceViewIdRegistry> > > >
             at egui-0.29.1/src/ui.rs:2271
  31: egui::ui::Ui::add_enabled_ui
             at egui-0.29.1/src/ui.rs:1676
      egui_tiles::tree::Tree<re_viewer_context::blueprint_id::BlueprintId<re_viewer_context::blueprint_id::SpaceViewIdRegistry> >::tile_ui<re_viewer_context::blueprint_id::BlueprintId<re_viewer_context::blueprint_id::SpaceViewIdRegistry> >
             at egui_tiles-0.10.1/src/tree.rs:389
  32: egui_tiles::container::tabs::Tabs::ui<re_viewer_context::blueprint_id::BlueprintId<re_viewer_context::blueprint_id::SpaceViewIdRegistry> >
             at egui_tiles-0.10.1/src/container/tabs.rs:203
  33: egui_tiles::tree::impl$1::tile_ui::closure$0
             at egui_tiles-0.10.1/src/tree.rs:397
      egui::ui::impl$7::add_enabled_ui::closure$0
             at egui-0.29.1/src/ui.rs:1680
      core::ops::function::FnOnce::call_once<egui::ui::impl$7::add_enabled_ui::closure_env$0<tuple$<>,egui_tiles::tree::impl$1::tile_ui::closure_env$0<re_viewer_context::blueprint_id::BlueprintId<re_viewer_context::blueprint_id::SpaceViewIdRegistry> > >,tuple$<
             at core/src/ops/function.rs:250
  34: alloc::boxed::impl$48::call_once<tuple$<ref_mut$<egui::ui::Ui> >,dyn$<core::ops::function::FnOnce<tuple$<ref_mut$<egui::ui::Ui> >,assoc$<Output,tuple$<> > > >,alloc::alloc::Global>      
             at alloc/src/boxed.rs:2022
  35: egui::ui::Ui::scope_dyn<tuple$<> >
             at egui-0.29.1/src/ui.rs:2292
  36: egui::ui::Ui::scope<tuple$<>,egui::ui::impl$7::add_enabled_ui::closure_env$0<tuple$<>,egui_tiles::tree::impl$1::tile_ui::closure_env$0<re_viewer_context::blueprint_id::BlueprintId<re_viewer_context::blueprint_id::SpaceViewIdRegistry> > > >
             at egui-0.29.1/src/ui.rs:2271
  37: egui::ui::Ui::add_enabled_ui
             at egui-0.29.1/src/ui.rs:1676
      egui_tiles::tree::Tree<re_viewer_context::blueprint_id::BlueprintId<re_viewer_context::blueprint_id::SpaceViewIdRegistry> >::tile_ui<re_viewer_context::blueprint_id::BlueprintId<re_viewer_context::blueprint_id::SpaceViewIdRegistry> >
             at egui_tiles-0.10.1/src/tree.rs:389
  38: egui_tiles::container::linear::Linear::horizontal_ui<re_viewer_context::blueprint_id::BlueprintId<re_viewer_context::blueprint_id::SpaceViewIdRegistry> >
             at egui_tiles-0.10.1/src/container/linear.rs:243
  39: egui_tiles::container::linear::Linear::ui
             at egui_tiles-0.10.1/src/container/linear.rs:227
      enum2$<egui_tiles::container::Container>::ui<re_viewer_context::blueprint_id::BlueprintId<re_viewer_context::blueprint_id::SpaceViewIdRegistry> >
             at egui_tiles-0.10.1/src/container/mod.rs:257
  40: egui_tiles::tree::impl$1::tile_ui::closure$0
             at egui_tiles-0.10.1/src/tree.rs:397
      egui::ui::impl$7::add_enabled_ui::closure$0
             at egui-0.29.1/src/ui.rs:1680
      core::ops::function::FnOnce::call_once<egui::ui::impl$7::add_enabled_ui::closure_env$0<tuple$<>,egui_tiles::tree::impl$1::tile_ui::closure_env$0<re_viewer_context::blueprint_id::BlueprintId<re_viewer_context::blueprint_id::SpaceViewIdRegistry> > >,tuple$<
             at core/src/ops/function.rs:250
  41: alloc::boxed::impl$48::call_once<tuple$<ref_mut$<egui::ui::Ui> >,dyn$<core::ops::function::FnOnce<tuple$<ref_mut$<egui::ui::Ui> >,assoc$<Output,tuple$<> > > >,alloc::alloc::Global>      
             at alloc/src/boxed.rs:2022
  42: egui::ui::Ui::scope_dyn<tuple$<> >
             at egui-0.29.1/src/ui.rs:2292
  43: egui::ui::Ui::scope<tuple$<>,egui::ui::impl$7::add_enabled_ui::closure_env$0<tuple$<>,egui_tiles::tree::impl$1::tile_ui::closure_env$0<re_viewer_context::blueprint_id::BlueprintId<re_viewer_context::blueprint_id::SpaceViewIdRegistry> > > >
             at egui-0.29.1/src/ui.rs:2271
  44: egui::ui::Ui::add_enabled_ui
             at egui-0.29.1/src/ui.rs:1676
      egui_tiles::tree::Tree<re_viewer_context::blueprint_id::BlueprintId<re_viewer_context::blueprint_id::SpaceViewIdRegistry> >::tile_ui<re_viewer_context::blueprint_id::BlueprintId<re_viewer_context::blueprint_id::SpaceViewIdRegistry> >
             at egui_tiles-0.10.1/src/tree.rs:389
  45: egui_tiles::tree::Tree<re_viewer_context::blueprint_id::BlueprintId<re_viewer_context::blueprint_id::SpaceViewIdRegistry> >::ui<re_viewer_context::blueprint_id::BlueprintId<re_viewer_context::blueprint_id::SpaceViewIdRegistry> >
             at egui_tiles-0.10.1/src/tree.rs:321
  46: core::ops::function::FnOnce::call_once<re_viewport::viewport::impl$0::viewport_ui::closure_env$1,tuple$<ref_mut$<egui::ui::Ui> > >
             at core/src/ops/function.rs:250
  47: alloc::boxed::impl$48::call_once<tuple$<ref_mut$<egui::ui::Ui> >,dyn$<core::ops::function::FnOnce<tuple$<ref_mut$<egui::ui::Ui> >,assoc$<Output,tuple$<> > > >,alloc::alloc::Global>      
             at alloc/src/boxed.rs:2022
  48: egui::ui::Ui::scope_dyn<tuple$<> >
             at egui-0.29.1/src/ui.rs:2292
  49: egui::ui::Ui::scope<tuple$<>,re_viewport::viewport::impl$0::viewport_ui::closure_env$1>   
             at egui-0.29.1/src/ui.rs:2271
  50: re_viewport::viewport::Viewport::viewport_ui
             at re_viewport/src/viewport.rs:138
  51: alloc::boxed::impl$48::call_once<tuple$<ref_mut$<egui::ui::Ui> >,dyn$<core::ops::function::FnOnce<tuple$<ref_mut$<egui::ui::Ui> >,assoc$<Output,tuple$<> > > >,alloc::alloc::Global>      
             at alloc/src/boxed.rs:2022
  52: egui::containers::panel::impl$8::show_inside_dyn::closure$1
             at egui-0.29.1/src/containers/panel.rs:1114
      core::ops::function::FnOnce::call_once<egui::containers::panel::impl$8::show_inside_dyn::closure_env$1<tuple$<> >,tuple$<ref_mut$<egui::ui::Ui> > >
             at core/src/ops/function.rs:250
  53: alloc::boxed::impl$48::call_once
             at alloc/src/boxed.rs:2022
      egui::containers::frame::Frame::show_dyn<tuple$<> >
             at egui-0.29.1/src/containers/frame.rs:283
  54: egui::containers::panel::CentralPanel::show_inside_dyn<tuple$<> >
             at egui-0.29.1/src/containers/panel.rs:1112
  55: re_viewer::app_state::AppState::show
             at re_viewer/src/app_state.rs:440
  56: re_viewer::app::impl$1::ui::closure$0
             at re_viewer/src/app.rs:980
      core::ops::function::FnOnce::call_once<re_viewer::app::impl$1::ui::closure_env$0,tuple$<ref_mut$<egui::ui::Ui> > >
             at core/src/ops/function.rs:250
  57: alloc::boxed::impl$48::call_once<tuple$<ref_mut$<egui::ui::Ui> >,dyn$<core::ops::function::FnOnce<tuple$<ref_mut$<egui::ui::Ui> >,assoc$<Output,tuple$<> > > >,alloc::alloc::Global>      
             at alloc/src/boxed.rs:2022
  58: egui::containers::panel::impl$8::show_inside_dyn::closure$1
             at egui-0.29.1/src/containers/panel.rs:1114
      core::ops::function::FnOnce::call_once<egui::containers::panel::impl$8::show_inside_dyn::closure_env$1<tuple$<> >,tuple$<ref_mut$<egui::ui::Ui> > >
             at core/src/ops/function.rs:250
  59: alloc::boxed::impl$48::call_once
             at alloc/src/boxed.rs:2022
      egui::containers::frame::Frame::show_dyn<tuple$<> >
             at egui-0.29.1/src/containers/frame.rs:283
  60: egui::containers::panel::CentralPanel::show_inside_dyn<tuple$<> >
             at egui-0.29.1/src/containers/panel.rs:1112
  61: egui::containers::panel::CentralPanel::show_dyn<tuple$<> >
             at egui-0.29.1/src/containers/panel.rs:1145
  62: re_viewer::app::impl$2::update
             at re_viewer/src/app.rs:1649
  63: egui::context::Context::run<eframe::native::epi_integration::impl$0::update::closure_env$0>
             at egui-0.29.1/src/context.rs:815
  64: eframe::native::epi_integration::EpiIntegration::update
             at eframe-0.29.1/src/native/epi_integration.rs:276
  65: eframe::native::wgpu_integration::impl$1::run_ui_and_paint
             at eframe-0.29.1/src/native/wgpu_integration.rs:372
  66: eframe::native::run::impl$1::window_event::closure$0
             at eframe-0.29.1/src/native/run.rs:283
      eframe::native::event_loop_context::with_event_loop_context<eframe::native::run::impl$1::window_event::closure_env$0<eframe::native::wgpu_integration::WgpuWinitApp> >
             at eframe-0.29.1/src/native/event_loop_context.rs:53
  67: eframe::native::run::impl$1::window_event<eframe::native::wgpu_integration::WgpuWinitApp> 
             at winit-0.30.5/src/platform_impl/windows/event_loop/runner.rs:236
      core::panic::unwind_safe::impl$25::call_once
             at winit-0.30.5/src/platform_impl/windows/event_loop/runner.rs:236
      core::panic::unwind_safe::impl$25::call_once
             at core/src/panic/unwind_safe.rs:272
      std::panicking::try::do_call
             at std/src/panicking.rs:559
      std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::windows::event_loop::runner::impl$3::call_event_handler::closure_env$0<winit::platform_impl::windows::event_loop::UserEventPlaceholder> > >
             at std/src/panicking.rs:523
  70: std::panic::catch_unwind
             at std/src/panic.rs:149
      winit::platform_impl::windows::event_loop::runner::EventLoopRunner<winit::platform_impl::windows::event_loop::UserEventPlaceholder>::catch_unwind<winit::platform_impl::windows::event_loop::UserEventPlaceholder,tuple$<>,winit::platform_impl::windows::event
             at winit-0.30.5/src/platform_impl/windows/event_loop/runner.rs:173
  71: winit::platform_impl::windows::event_loop::runner::EventLoopRunner<winit::platform_impl::windows::event_loop::UserEventPlaceholder>::call_event_handler
             at winit-0.30.5/src/platform_impl/windows/event_loop/runner.rs:230
      winit::platform_impl::windows::event_loop::runner::EventLoopRunner<winit::platform_impl::windows::event_loop::UserEventPlaceholder>::send_event<winit::platform_impl::windows::event_loop::UserEventPlaceholder>
             at winit-0.30.5/src/platform_impl/windows/event_loop/runner.rs:210
  72: winit::platform_impl::windows::event_loop::public_window_callback_inner::closure$4
             at winit-0.30.5/src/platform_impl/windows/event_loop.rs:1178
  73: core::ops::function::FnOnce::call_once
             at core/src/ops/function.rs:250
      core::panic::unwind_safe::impl$25::call_once
             at core/src/panic/unwind_safe.rs:272
      std::panicking::try::do_call
             at std/src/panicking.rs:559
      std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::windows::event_loop::public_window_callback_inner::closure_env$4> >
             at std/src/panicking.rs:523
  74: std::panic::catch_unwind
             at std/src/panic.rs:149
      winit::platform_impl::windows::event_loop::runner::EventLoopRunner<winit::platform_impl::windows::event_loop::UserEventPlaceholder>::catch_unwind<winit::platform_impl::windows::event_loop::UserEventPlaceholder,tuple$<>,winit::platform_impl::windows::event
             at winit-0.30.5/src/platform_impl/windows/event_loop/runner.rs:173
  75: winit::platform_impl::windows::event_loop::public_window_callback_inner
             at winit-0.30.5/src/platform_impl/windows/event_loop.rs:2358
      winit::platform_impl::windows::event_loop::public_window_callback
             at winit-0.30.5/src/platform_impl/windows/event_loop.rs:1019
  76: DispatchMessageW
  77: CallWindowProcW
  78: windows::Win32::UI::WindowsAndMessaging::CallWindowProcW
             at windows-0.54.0/src/Windows/Win32/UI/WindowsAndMessaging/mod.rs:118
      accesskit_windows::subclass::wnd_proc
             at accesskit_windows-0.22.0/src/subclass.rs:73
  79: DispatchMessageW
  80: DispatchMessageW
  81: GetClassLongW
  82: KiUserCallbackDispatcher
  83: NtUserDispatchMessage
  84: DispatchMessageW
  85: winit::platform_impl::windows::event_loop::EventLoop<enum2$<eframe::native::winit_integration::UserEvent> >::dispatch_peeked_messages<enum2$<eframe::native::winit_integration::UserEvent> >
             at winit-0.30.5/src/platform_impl/windows/event_loop.rs:478
  86: winit::platform_impl::windows::event_loop::EventLoop<enum2$<eframe::native::winit_integration::UserEvent> >::run_on_demand<enum2$<eframe::native::winit_integration::UserEvent>,winit::platform::run_on_demand::EventLoopExtRunOnDemand::run_app_on_demand::clo
             at winit-0.30.5/src/platform_impl/windows/event_loop.rs:265
  87: eframe::native::run::run_wgpu::closure$0
             at eframe-0.29.1/src/native/run.rs:357
      eframe::native::run::with_event_loop::closure$0
             at eframe-0.29.1/src/native/run.rs:52
      std::thread::local::LocalKey<core::cell::RefCell<enum2$<core::option::Option<winit::event_loop::EventLoop<enum2$<eframe::native::winit_integration::UserEvent> > > > > >::try_with
             at std/src/thread/local.rs:286
      std::thread::local::LocalKey<core::cell::RefCell<enum2$<core::option::Option<winit::event_loop::EventLoop<enum2$<eframe::native::winit_integration::UserEvent> > > > > >::with
             at std/src/thread/local.rs:262
      eframe::native::run::with_event_loop
             at eframe-0.29.1/src/native/run.rs:42
      eframe::native::run::run_wgpu
             at eframe-0.29.1/src/native/run.rs:355
  88: eframe::run_native
             at eframe-0.29.1/src/lib.rs:265
```

**Comment by emilk** [comment]
* Closed by https://github.com/rerun-io/rerun/pull/7777
