### ISSUE TITLE
Debug-only crash when setting "Force Center's strength" to a large value

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#8503]
`emath` crashes on a debug assertion because the direction is supposedly not normalized.

Backtrace:
```
thread 'main' panicked at 'expected normalized direction'
emath/src/rect.rs:680
stack backtrace:
   6: core::panicking::panic_fmt
             at core/src/panicking.rs:72:14
   7: emath::rect::Rect::intersects_ray_from_center
             at emath/src/rect.rs:680:9
   8: re_view_graph::layout::provider::line_segment
             at re_view_graph/src/layout/provider.rs:311:24
      re_view_graph::layout::provider::ForceLayoutProvider::layout
             at re_view_graph/src/layout/provider.rs:212:39
      re_view_graph::layout::provider::ForceLayoutProvider::tick
             at re_view_graph/src/layout/provider.rs:294:9
   9: re_view_graph::ui::state::LayoutState::update
             at re_view_graph/src/ui/state.rs:156:34
      re_view_graph::ui::state::LayoutState::get
             at re_view_graph/src/ui/state.rs:170:17
  10: <re_view_graph::view::GraphView as re_viewer_context::view::view_class::ViewClass>::ui
             at re_view_graph/src/view.rs:182:22
```

Offending emath code:
https://github.com/emilk/egui/blob/8c4d8b2da8c108d0fe67f16dddc686ac6bf58eae/crates/emath/src/rect.rs#L679-L684
```rust
pub fn intersects_ray_from_center(&self, d: Vec2) -> Pos2 {
    debug_assert!(d.is_normalized(), "expected normalized direction");

    // ...
```

The sad part is that the direction is indeed normalized as far as I can tell.. they just don't seem to agree on the definition of normalized:
```rust
  // Calculate direction vector from source to target
  let direction = (target_center - source_center).normalized();

  // Find the border points on both rectangles
  let source_point = source.intersects_ray_from_center(direction);
  let target_point = target.intersects_ray_from_center(-direction); // Reverse direction for target
```

**Comment by grtlr** [comment]
@lucasmerlin @emilk FYI: There seems to be something fishy with my implementation of `is_normalized`.

**Comment by grtlr** [comment]
So the reason why this happened is because `.normalized()` returns zero if input is zero.

This can happen in layouts, if two nodes accidentally end up in the same spot :

In #8505, I've added checks to avoid this computation altogether, which should fix this bug.
