### ISSUE TITLE
Unstable test, `re_arrow_store::store_polars::to_dataframe` fails

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#894]
**Describe the bug**
Test instability on CI. One instance of it:
https://github.com/rerun-io/rerun/actions/runs/3995045925/jobs/6853468210

**Backtrace**
```
 thread 'gc_correct' panicked at 'called `Option::unwrap()` on a `None` value', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/polars-core-0.26.1/src/utils/mod.rs:601:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:775:21
   4: polars_core::utils::concat_df
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/polars-core-0.26.1/src/utils/mod.rs:601:22
   5: polars_core::functions::diag_concat_df
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/polars-core-0.26.1/src/functions.rs:289:5
   6: re_arrow_store::store_polars::<impl re_arrow_store::store::DataStore>::to_dataframe
             at ./src/store_polars.rs:94:18
   7: correctness::gc_correct
             at ./tests/correctness.rs:377:9
   8: correctness::gc_correct::{{closure}}
             at ./tests/correctness.rs:345:1
   9: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by emilk** [comment]
I don't think this is fixed
